### ISSUE TITLE
Can this plugin be merged to vim runtime?

### ISSUE THREAD

**Issue by Freed-Wu** [raimon49/requirements.txt.vim#19]
Can this plugin be merged to [vim runtime](https://github.com/vim/vim/tree/master/runtime)? I think it can help more people. Thanks!

**Comment by raimon49** [comment]
@Freed-Wu Thanks for the suggestion. Not planned for now.

For example, a generator like [Vim Bootstrap](https://vim-bootstrap.com/) can use this plugin from the start. That is enough for now, in my opinion.
