### ISSUE TITLE
Plugin doesnt work in neovim 0.8.0

### ISSUE THREAD

**Issue by johnmathews** [raimon49/requirements.txt.vim#20]
It definitely used to work just fine. There aren't any error messages so I'm sorry I dont have anything more useful to tell you.

**Comment by raimon49** [comment]
Thanks for the report.

NeoVim 0.8.0 seems to be the development version as of 2022-09.
https://github.com/neovim/neovim/releases

I will use it too when it is released as a stable version.

**Comment by Freed-Wu** [comment]
```vim
#!/usr/bin/env -S vi requirements.txt -u
" $ uname -r
" 5.19.7-arch1-1
" $ has
" ✓ vi 0.7.2
" $ cat test.vim
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/raimon49/requirements.txt.vim
syntax on
" $ chmod +x test.vim
" $ ./test.vim
```

```txt
#!/usr/bin/env -S pip install -r
gpustat==1.0.0  # debug
ptpython  # debug
pudb  # debug
pytorch_lightning  # pl.seed_everything()
rich  # beautify
# thop  # profile(), clever_format()
tqdm  # https://github.com/Textualize/rich/issues/2445
```

![Screenshot from 2022-10-05 14-52-34](https://user-images.githubusercontent.com/32936898/193998631-1f92b131-91cc-4c96-a6e0-effbcfb36428.png)

Why the comment don't be highlighted?

And if user `colorscheme XXX`, all highlight will disappear.

![Screenshot from 2022-10-05 14-53-29](https://user-images.githubusercontent.com/32936898/193998853-21bf0692-0087-45ea-9070-88080706e14c.png)

Is it a bug?

**Comment by raimon49** [comment]
@Freed-Wu It may be a bug in detecting file names.

When you run the following command in Vim, what is output and highlighted?

```vim
:setl ft?

:setl ft=requirements
```

**Comment by Freed-Wu** [comment]
> It may be a bug in detecting file names.

No, the result of `set ft` is right `requirements`.

> Why the comment don't be highlighted?

This is comment and packagename has same color.

![Screenshot from 2022-10-06 13-42-35](https://user-images.githubusercontent.com/32936898/194223572-6150888f-4010-499f-a735-a31a0ca29999.png)

> And if user colorscheme XXX, all highlight will disappear.

```vim
#!/usr/bin/env -S vi requirements.txt -u
" $ uname -r
" 5.19.7-arch1-1
" $ has
" ✓ vi 0.7.2
" $ cat test.vim
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/raimon49/requirements.txt.vim
syntax on
autocmd VimEnter * colorscheme default
" $ chmod +x test.vim
" $ ./test.vim
```

I have found the reason of this bug. I'll push a PR.

**Comment by raimon49** [comment]
@johnmathews I have been using NeoVim 0.8 since it was officially released.It seems to be working fine.

![image](https://user-images.githubusercontent.com/221802/194310286-1ae3c6bd-9cde-4c32-91fd-04bac2f00f95.png)

```bash
$ nvim --version
NVIM v0.8.0-1210-gd367ed9b2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az505-656
```

Also, this plugin has been updated. Please try the latest plugin as well.

**Comment by Freed-Wu** [comment]
I use neovim 0.72. I can guarantee it can work normally.

![Screenshot from 2022-10-07 12-16-49](https://user-images.githubusercontent.com/32936898/194466946-796bdef7-db6f-4213-b939-aead96adfe92.png)
