### ISSUE TITLE
feat: add support `gx`

### ISSUE THREAD

**Issue by davidosomething** [raimon49/requirements.txt.vim#3]
With netrw enabled, `gx` usually goes to urls like `http://google.com/` if it is used on that url in a file

When on a package name in `requirements.txt` it would be cool if `gx` opened up the pypi package url for that package, e.g. https://pypi.org/project/simplejson/ when `gx` on simplejson

**Comment by raimon49** [comment]
Thank you for your suggestion.

I want to try the implementation of this feature.

**Comment by Freed-Wu** [comment]
Hey. This function has other packages can do:

1. use `gx` to open a URL: `netrw` or [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc)
2. use `g/` (for me) to search a keyword: [voldikss/vim-browser-search](https://github.com/voldikss/vim-browser-search) or [open-browser.vim](https://github.com/tyru/open-browser.vim)

I guess you want the second? You can see <https://github.com/voldikss/vim-browser-search#gbrowser_search_engines>:

``````markdown
#### **`g:browser_search_engines`**

Default:

```vim
  {
  \ 'arxiv':         'https://arxiv.org/search/?query=%s&searchtype=all',
  \ 'baidu':         'https://www.baidu.com/s?ie=UTF-8&wd=%s',
  \ 'bing':          'https://www.bing.com/search?q=%s',
  \ 'bilibili':      'https://search.bilibili.com/all?keyword=%s',
  \ 'ctan':          'https://ctan.org/search?phrase=%s',
  \ 'cpan':          'https://metacpan.org/search?q=%s',
  \ 'csdn':          'https://so.csdn.net/so/search?q=%s',
  \ 'dlbp':          'https://dblp.org/search?q=%s',
  \ 'duckduckgo':    'https://duckduckgo.com/?q=%s',
  \ 'github':        'https://github.com/search?q=%s',
  \ 'google':        'https://google.com/search?q=%s',
  \ 'mdn':           'https://developer.mozilla.org/en-US/search?q=%s',
  \ 'npm':           'https://www.npmjs.com/search?q=%s',
  \ 'pypi':          'https://pypi.org/search/?q=%s',
  \ 'scholar':       'https://scholar.google.com/scholar?q=%s',
  \ 'stackoverflow': 'https://stackoverflow.com/search?q=%s',
  \ 'translate':     'https://translate.google.com/?sl=auto&tl=it&text=%s',
  \ 'wikipedia':     'https://en.wikipedia.org/wiki/%s',
  \ 'youtube':       'https://www.youtube.com/results?search_query=%s&page=&utm_source=opensearch',
  \ }
```
``````

Note `pypi`.
