### ISSUE TITLE
Unknown function: requirements#shebang

### ISSUE THREAD

**Issue by naggie** [raimon49/requirements.txt.vim#37]
![image](https://github.com/raimon49/requirements.txt.vim/assets/208440/c411419d-326b-4b19-94ba-a82ae8c458bc)

Hi, 

I seem to be getting an error related to the latest commit, specifically this change: https://github.com/raimon49/requirements.txt.vim/commit/065c3e13da77040e6a3df8002c9fdc9b1fb63cd2#diff-5152a459f9b30504e4d1dcbbd06ed6d475cbc342c4176f1fb2a83790e22cf240

I've reverted to an older commit to now and it works.

Thanks!

**Comment by Freed-Wu** [comment]
Can you provide a minimal vimrc to reproduce this bug? I cannot reproduce it.

**Comment by Freed-Wu** [comment]
Similar with #38.
