### ISSUE TITLE
Unable to install using dein.vim plugin manager

### ISSUE THREAD

**Issue by rafi** [raimon49/requirements.txt.vim#4]
Ideally the function `requirements#matched_filename` should be _defined_ in `ftdetect/requirements.vim` in-order for plugin-managers that support lazy-loading to work. (For example [dein.vim](https://github.com/Shougo/dein.vim)) Otherwise I see errors such as:

> Error detected while processing function <SNR>26_isRequirementsFile:
> line    3:
> E117: Unknown function: requirements#matched_filename
> E15: Invalid expression: requirements#matched_filename(l:filename)

**Comment by raimon49** [comment]
@rafi Hi, I tried to fix this issue. Could you try to use the branch `fix-load-script-order`?

**Comment by rafi** [comment]
@raimon49 it works with mentioned branch, thanks!

**Comment by rafi** [comment]
Oops, too soon. When opening a txt file I'm getting:

> Error detected while processing function <SNR>19_isRequirementsFile[3]..Requirements_matched_filename:
> line    9:
> E121: Undefined variable: g:requirements#detect_filename_pattern
> E116: Invalid arguments for function len(g:requirements#detect_filename_pattern) && a:filename =~# g:requirements#detect_filename_pattern
> E15: Invalid expression: len(g:requirements#detect_filename_pattern) && a:filename =~# g:requirements#detect_filename_pattern

**Comment by rafi** [comment]
Revision 276d714 fixes this last issue. thank you!

**Comment by raimon49** [comment]
OK, thank you for reporting. I will merge to `master` .
