### ISSUE TITLE
Add support of package names as URLs

### ISSUE THREAD

**Issue by atugushev** [raimon49/requirements.txt.vim#9]
Would be nice to colorize URLs.

![image](https://user-images.githubusercontent.com/7377671/57265071-f5f38900-709f-11e9-9b9d-9519c2017a51.png)

**Comment by raimon49** [comment]
Thanks for the feedback. I’ll consider it.

**Comment by raimon49** [comment]
@atugushev Hi, I have released the latest version.

URL detection has been improved.
![colorized-url](https://user-images.githubusercontent.com/221802/57343386-23166900-717e-11e9-88ba-385f47c11c43.png)

Please try using the latest master branch.
